export const INGREDIENT_CHARACTERISTIC_SET: 'INGREDIENT_CHARACTERISTIC_SET' = 'INGREDIENT_CHARACTERISTIC_SET';
export const INGREDIENT_CHARACTERISTIC_RESET: 'INGREDIENT_CHARACTERISTIC_RESET' = 'INGREDIENT_CHARACTERISTIC_RESET';
