export const GET_INGREDIENTS_API_REQUEST: 'GET_INGREDIENTS_API_REQUEST' = 'GET_INGREDIENTS_API_REQUEST';
export const GET_INGREDIENTS_API_SUCCESS: 'GET_INGREDIENTS_API_SUCCESS' = 'GET_INGREDIENTS_API_SUCCESS';
export const GET_INGREDIENTS_API_ERROR: 'GET_INGREDIENTS_API_ERROR' = 'GET_INGREDIENTS_API_ERROR';
