export const SELECTION_INGREDIENT_ADD: 'SELECTION_INGREDIENT_ADD' = 'SELECTION_INGREDIENT_ADD';
export const SELECTION_INGREDIENT_DELETE: 'SELECTION_INGREDIENT_DELETE' = 'SELECTION_INGREDIENT_DELETE';
export const SELECTION_INGREDIENT_REORDER: 'SELECTION_INGREDIENT_REORDER' = 'SELECTION_INGREDIENT_REORDER';
export const SELECTION_INGREDIENT_RESET: 'SELECTION_INGREDIENT_RESET' = 'SELECTION_INGREDIENT_RESET';
