export const PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST' = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS' = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_ERROR: 'PASSWORD_RESET_ERROR' = 'PASSWORD_RESET_ERROR';

export const PASSWORD_CREATE_NEW_REQUEST: 'PASSWORD_CREATE_NEW_REQUEST' = 'PASSWORD_CREATE_NEW_REQUEST';
export const PASSWORD_CREATE_NEW_SUCCESS: 'PASSWORD_CREATE_NEW_SUCCESS' = 'PASSWORD_CREATE_NEW_SUCCESS';
export const PASSWORD_CREATE_NEW_ERROR: 'PASSWORD_CREATE_NEW_ERROR' = 'PASSWORD_CREATE_NEW_ERROR';

export const REGISTRATION_USER_REQUEST: 'REGISTRATION_USER_REQUEST' = 'REGISTRATION_USER_REQUEST';
export const REGISTRATION_USER_SUCCESS: 'REGISTRATION_USER_SUCCESS' = 'REGISTRATION_USER_SUCCESS';
export const REGISTRATION_USER_ERROR: 'REGISTRATION_USER_ERROR' = 'REGISTRATION_USER_ERROR';

export const AUTHENTICATION_USER_REQUEST: 'AUTHENTICATION_USER_REQUEST' = 'AUTHENTICATION_USER_REQUEST';
export const AUTHENTICATION_USER_SUCCESS: 'AUTHENTICATION_USER_SUCCESS' = 'AUTHENTICATION_USER_SUCCESS';
export const AUTHENTICATION_USER_ERROR: 'AUTHENTICATION_USER_ERROR' = 'AUTHENTICATION_USER_ERROR';

export const LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST' = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS' = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR' = 'LOGOUT_USER_ERROR';

export const RENEWAL_TOKEN_REQUEST: 'RENEWAL_TOKEN_REQUEST' = 'RENEWAL_TOKEN_REQUEST';
export const RENEWAL_TOKEN_SUCCESS: 'RENEWAL_TOKEN_SUCCESS' = 'RENEWAL_TOKEN_SUCCESS';
export const RENEWAL_TOKEN_ERROR: 'RENEWAL_TOKEN_ERROR' = 'RENEWAL_TOKEN_ERROR';

export const RENEWAL_INFO_USER_REQUEST: 'RENEWAL_INFO_USER_REQUEST' = 'RENEWAL_INFO_USER_REQUEST';
export const RENEWAL_INFO_USER_SUCCESS: 'RENEWAL_INFO_USER_SUCCESS' = 'RENEWAL_INFO_USER_SUCCESS';
export const RENEWAL_INFO_USER_ERROR: 'RENEWAL_INFO_USER_ERROR' = 'RENEWAL_INFO_USER_ERROR';

export const UPDATE_INFO_USER_REQUEST: 'UPDATE_INFO_USER_REQUEST' = 'UPDATE_INFO_USER_REQUEST';
export const UPDATE_INFO_USER_SUCCESS: 'UPDATE_INFO_USER_SUCCESS' = 'UPDATE_INFO_USER_SUCCESS';
export const UPDATE_INFO_USER_ERROR: 'UPDATE_INFO_USER_ERROR' = 'UPDATE_INFO_USER_ERROR';
