export const WS_PERSON_START: 'WS_PERSON_START' = 'WS_PERSON_START';
export const WS_PERSON_OPEN: 'WS_PERSON_OPEN' = 'WS_PERSON_OPEN';
export const WS_PERSON_SUCCESS: 'WS_PERSON_SUCCESS' = 'WS_PERSON_SUCCESS'; 
export const WS_PERSON_CLOSED: 'WS_PERSON_CLOSED' = 'WS_PERSON_CLOSED';
export const WS_PERSON_DISCONNECT: 'WS_PERSON_DISCONNECT' = 'WS_PERSON_DISCONNECT';
export const WS_PERSON_ERROR: 'WS_PERSON_ERROR' = 'WS_PERSON_ERROR';
export const WS_PERSON_GET_MESSAGE: 'WS_PERSON_GET_MESSAGE' = 'WS_PERSON_GET_MESSAGE';
